#!/usr/bin/env bash

set -euo pipefail

# Concise, inefficient:
# grep -oP '[ATGC]' | sort | uniq -c | awk '{print $1}' | paste -sd ' ' -

# Wordy, efficient:
awk -f "$(dirname $(realpath "$0"))/dna.awk"
