#!/usr/bin/env bash

set -euo pipefail

# read -r S1
# read -r S2

# paste -d '' <(echo "$S1" | sed 's/./&\n/g') \
#             <(echo "$S2" | sed 's/./&\n/g') \
#     | grep -vE '([ACGT])\1' \
#     | grep -c .

awk -f "$(dirname $(realpath "$0"))/hamm.awk"
