#!/usr/bin/env bash

set -euo pipefail

# IN=$(cat)
# S1=$(echo "$IN" | sed -ne 1p)
# S2=$(echo "$IN" | sed -ne 2p)

# paste -d '' <(echo "$S1" | sed 's/./&\n/g') \
#             <(echo "$S2" | sed 's/./&\n/g') \
#     | grep -vE '([ACGT])\1' \
#     | grep -c .

awk -f "$(dirname $(realpath "$0"))/hamm.awk"
