#!/usr/bin/env bash

set -euo pipefail

function calc() {
    dc -e "10 k" \
       -e "$1" \
       -e "n"
}

read -r AA Aa aa

POP=$(calc "$AA $Aa $aa + +")

# Homozygous: P(XX) = N(X)/POP * (N(X)-1)/(POP-1)
P_AAAA=$(calc "$AA $POP / $AA 1 - $POP 1 - / *")
P_AaAa=$(calc "$Aa $POP / $Aa 1 - $POP 1 - / *")
P_aaaa=$(calc "$aa $POP / $aa 1 - $POP 1 - / *")

# Heterozygous: P(XY) = N(X)/POP * N(Y)/(POP-1)
P_AAaa=$(calc "$AA $POP / $aa $POP 1 - / *")
P_aaAA=$(calc "$aa $POP / $AA $POP 1 - / *")

P_AAAa=$(calc "$AA $POP / $Aa $POP 1 - / *")
P_AaAA=$(calc "$Aa $POP / $AA $POP 1 - / *")

P_Aaaa=$(calc "$Aa $POP / $aa $POP 1 - / *")
P_aaAa=$(calc "$aa $POP / $Aa $POP 1 - / *")

# Chances of having at least one dominant gene:
#     AA   Aa   aa
# AA   1    1    1
# Aa   1  3/4  1/4
# aa   1  1/4    0

RES=$(calc "
    $P_AAAA 1 *
    $P_AAAa 1 *
    $P_AaAA 1 *
    $P_AAaa 1 *
    $P_aaAA 1 *

    $P_AaAa 0.75 *

    $P_Aaaa 0.5 *
    $P_aaAa 0.5 *

    $P_aaaa 0 *

    + + + + + + + +
")

printf "%.5f\n" "$RES"
