#!/usr/bin/env bash

set -euo pipefail

tr -dc AUGC \
| grep -oPm1 'AUG(...)*?(UAA|UAG|UGA)' | head -1 \
| grep -o ... \
| sed -E \
    -e 's/(GC.)/A/' \
    -e 's/(UGC|UGU)/C/' \
    -e 's/(GAC|GAU)/D/' \
    -e 's/(GAA|GAG)/E/' \
    -e 's/(UUC|UUU)/F/' \
    -e 's/(GG.)/G/' \
    -e 's/(CAC|CAU)/H/' \
    -e 's/(AUA|AUC|AUU)/I/' \
    -e 's/(AAA|AAG)/K/' \
    -e 's/(CU.|UUA|UUG)/L/' \
    -e 's/(AUG)/M/' \
    -e 's/(AAU|AAC)/N/' \
    -e 's/(CC.)/P/' \
    -e 's/(CAA|CAG)/Q/' \
    -e 's/(AGA|AGG|CG.)/R/' \
    -e 's/(AGC|AGU|UC.)/S/' \
    -e 's/(AC.)/T/' \
    -e 's/(GU.)/V/' \
    -e 's/(UGG)/W/' \
    -e 's/(UAC|UAU)/Y/' \
    -e 's/(UAA|UAG|UGA)//' \
| tr -d '\n'
echo
